name: Build GUI with PyInstaller

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
      - '1fichier_gui.spec'
      - 'requirements.txt'
      - '.github/workflows/pyinstaller-build.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        default: '3.12'
      build-mode:
        description: 'normal or clean'
        required: false
        default: 'normal'

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    env:
      SPEC_FILE: 1fichier_gui.spec
      DIST_NAME: 1fichier_gui
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ github.event.inputs.python-version || '3.12' }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: pip-${{ runner.os }}-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Show versions
        run: |
          python --version
          pyinstaller --version

      - name: Optional clean
        if: ${{ github.event.inputs.build-mode == 'clean' }}
        run: |
          Remove-Item -Recurse -Force build,dist -ErrorAction SilentlyContinue
          Get-ChildItem -Recurse -Filter *.spec | ForEach-Object { Write-Host "Spec: $($_.FullName)" }

      - name: Build (spec)
        run: |
          if (-not (Test-Path $env:SPEC_FILE)) { Write-Error "Spec file '$env:SPEC_FILE' not found" }
          pyinstaller $env:SPEC_FILE --noconfirm

      - name: List dist
        run: |
          Get-ChildItem -Recurse .\dist | Select-Object FullName,Length | Format-Table -AutoSize
      - name: Locate exe
        id: locate
        run: |
          $folder = Get-ChildItem dist | Where-Object { $_.PsIsContainer } | Select-Object -First 1 -ExpandProperty Name
          if (-not $folder) { Write-Error 'No dist folder found' }
          $exe = Join-Path dist "$folder/${{ env.DIST_NAME }}.exe"
          if (-not (Test-Path $exe)) { Write-Error "Executable not found at $exe" }
          echo "EXE_PATH=$exe" >> $env:GITHUB_ENV
          Write-Host "Found EXE: $exe"

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.DIST_NAME }}-exe-win64
          path: ${{ env.DIST_NAME }}.spec
          if-no-files-found: warn
      - name: Upload exe real
        uses: actions/upload-artifact@v4
        with:
            name: ${{ env.DIST_NAME }}-raw-exe
            path: ${{ env.EXE_PATH }}
            if-no-files-found: error

      - name: (Optional) Draft release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ env.EXE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
